-- CRIAÇÃO DE TABELAS DO SUPERMERCADO

CREATE TABLE SUPERMERCADO
(
CODIGO_LOJA INT NOT NULL,
NOME_LOJA VARCHAR (50) NOT NULL,
CNPJ_LOJA CHAR (14) NOT NULL,
INSCRICAO_ESTADUAL VARCHAR (50) NOT  NULL,
CODIGO_ENDERECO INT NOT  NULL,
PRIMARY KEY (CODIGO_LOJA),
UNIQUE KEY (CNPJ_LOJA),
UNIQUE KEY (INSCRICAO_ESTADUAL),
UNIQUE KEY (CODIGO_ENDERECO),
FOREIGN KEY (CODIGO_ENDERECO) REFERENCES ENDERECO (CODIGO_ENDERECO)
);


-- TABELA ENDERECO
CREATE TABLE ENDERECO
(
CODIGO_ENDERECO INT NOT NULL,
CEP CHAR (8) NOT NULL,
CIDADE VARCHAR (50) NOT NULL,
ESTADO CHAR (2) NOT NULL,
BAIRRO VARCHAR (50) NOT NULL,
NUMERO INT NULL,
COMPLEMENTO CHAR (30) NULL,
PRIMARY KEY (CODIGO_ENDERECO)
);


-- TABELA CLIENTE_ENDERECO
CREATE TABLE CLIENTE_ENDERECO
(
CODIGO_CLIENTE INT NULL,
CODIGO_CLIENTE_PJ INT NULL,
CODIGO_ENDERECO INT NOT NULL,
UNIQUE KEY (CODIGO_CLIENTE, CODIGO_ENDERECO),
FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE_PF (CODIGO_CLIENTE),
FOREIGN KEY (CODIGO_CLIENTE_PJ) REFERENCES CLIENTE_PJ (CODIGO_CLIENTE_PJ),
FOREIGN KEY (CODIGO_ENDERECO) REFERENCES ENDERECO (CODIGO_ENDERECO)
);

-- TABELA CLIENTE PESSOA FÍSICA
CREATE TABLE CLIENTE_PF
(
CODIGO_CLIENTE INT NOT NULL,
CPF CHAR(11) NOT NULL,
NOME VARCHAR (100) NOT NULL,
DATA_NASCIMENTO DATE NOT NULL,
RG CHAR(10) NOT NULL,
GENERO CHAR(10) NULL,
EMAIL VARCHAR(100) NOT NULL,
PRIMARY KEY (CODIGO_CLIENTE),
UNIQUE KEY (CPF)
);

-- TABELA CLIENTE PESSOA JURÍDICA
CREATE TABLE CLIENTE_PJ
(
CODIGO_CLIENTE_PJ INT NOT NULL,
CNPJ CHAR(11) NOT NULL,
RAZAO_SOCIAL VARCHAR(100) NULL,
EMAIL VARCHAR(100) NOT NULL,
PRIMARY KEY (CODIGO_CLIENTE_PJ),
UNIQUE KEY (CNPJ)
);


-- TABELA TIPO DE LOJA
CREATE TABLE TIPO_LOJA
(
CODIGO_TIPO_LOJA INT NOT NULL,
TIPO_LOJA VARCHAR (50) NOT NULL,
PRIMARY KEY (CODIGO_TIPO_LOJA)
);


-- TABELA DE PRODUTO
CREATE TABLE PRODUTO
(
CODIGO_PRODUTO INT NOT NULL,
NOME_PRODUTO VARCHAR(150) NOT NULL,
FORNECEDOR VARCHAR(150) NOT NULL,
CODIGO_CATEGORIA INT NOT NULL,
CODIGO_MARCA  INT  NOT NULL,
QUANTIDADE_UNITARIA INT NOT NULL,
PESO DECIMAL(12,3) NOT NULL,
PRIMARY KEY (CODIGO_PRODUTO),
UNIQUE KEY (NOME_PRODUTO),
FOREIGN KEY (CODIGO_CATEGORIA) REFERENCES CATEGORIA (CODIGO_CATEGORIA),
FOREIGN KEY (CODIGO_MARCA) REFERENCES MARCA (CODIGO_MARCA)
);


-- TABELA CATEGORIA DE PRODUTO
CREATE TABLE CATEGORIA
(
CODIGO_CATEGORIA INT NOT NULL,
TIPO_CATEGORIA VARCHAR(100) NOT NULL,
PRIMARY KEY (CODIGO_CATEGORIA)
);


-- TABELA DE MARCA
CREATE TABLE MARCA
(
CODIGO_MARCA INT NOT NULL,
NOME_MARCA VARCHAR(100) NOT NULL,
PRIMARY KEY (CODIGO_MARCA)
);


-- TABELA DE ESTOQUE
CREATE TABLE ESTOQUE
(
CODIGO_ESTOQUE INT NOT NULL,
CODIGO_PRODUTO INT NOT NULL,
CODIGO_LOJA INT NOT NULL,
QUANTIDADE INT NOT NULL,
PRIMARY KEY (CODIGO_ESTOQUE, CODIGO_PRODUTO, CODIGO_LOJA),
FOREIGN KEY (CODIGO_PRODUTO) REFERENCES PRODUTO (CODIGO_PRODUTO),
FOREIGN KEY (CODIGO_LOJA) REFERENCES SUPERMERCADO (CODIGO_LOJA)
);


-- TABELA DE PREÇO DE COMPRA
CREATE TABLE PRECO_COMPRA
(
CODIGO_PRECO_COMPRA INT NOT NULL,
CODIGO_PRODUTO INT NOT NULL,
DATA_VIGENCIA_COMPRA DATE NOT NULL,
VALOR_PRECO DECIMAL(12,4) NOT NULL,
PRIMARY KEY (CODIGO_PRODUTO, CODIGO_PRECO_COMPRA, DATA_VIGENCIA_COMPRA),
FOREIGN KEY (CODIGO_PRODUTO) REFERENCES PRODUTO (CODIGO_PRODUTO)
);


-- TABELA DE PREÇO DE VENDA
CREATE TABLE PRECO_VENDA
(
CODIGO_PRECO_VENDA INT NOT NULL,
CODIGO_PRODUTO INT  NOT NULL,
CODIGO_LOJA INT  NOT NULL,
DATA_VIGENCIA_VENDA DATE  NOT NULL,
VALOR_PRECO  DECIMAL(12,4)  NOT NULL,
PRIMARY KEY (CODIGO_PRECO_VENDA, CODIGO_PRODUTO, CODIGO_LOJA, DATA_VIGENCIA_VENDA),
FOREIGN KEY (CODIGO_PRODUTO) REFERENCES PRODUTO (CODIGO_PRODUTO),
FOREIGN KEY (CODIGO_LOJA) REFERENCES SUPERMERCADO (CODIGO_LOJA)
);


-- TABELA DE NOTA FISCAL
CREATE TABLE NF
(
CODIGO_NF INT NOT NULL,
CODIGO_TIPO_LOJA INT NOT NULL,
NUMERO_SERIE CHAR(3) NOT NULL,
NUMERO CHAR(9) NOT NULL,
CHAVE_ACESSO CHAR(44) NOT NULL,
DATA_EMISSAO DATE NOT NULL,
CODIGO_PAGTO INT NOT NULL,
VALOR_FRETE DECIMAL(12,4) NULL,
PRIMARY KEY (CODIGO_NF, CODIGO_TIPO_LOJA),
FOREIGN KEY (CODIGO_TIPO_LOJA) REFERENCES TIPO_LOJA (CODIGO_TIPO_LOJA),
FOREIGN KEY (CODIGO_PAGTO) REFERENCES FORMA_PAGAMENTO (CODIGO_PAGTO)
);

SELECT * FROM NF;



-- TABELA DE FORMA DE PAGAMENTO
CREATE TABLE FORMA_PAGAMENTO
(
CODIGO_PAGTO INT NOT NULL,
DESCRICAO_PAGTO VARCHAR(50) NOT NULL,
PRIMARY KEY (CODIGO_PAGTO)
);


-- TABELA DE ITENS DE PRODUTOS DE NOTA FISCAL
CREATE TABLE ITENS_NF
(
CODIGO_ITEM INT NOT NULL,
CODIGO_PRODUTO INT NOT NULL,
CODIGO_NF INT NOT NULL,
PRECO_UNITARIO DECIMAL(12,4) NOT NULL,
PERCENTUAL_DESCONTO DECIMAL(5,2) NULL,
PRECO_DESCONTO DECIMAL(12,4) NULL,
QUANTIDADE_PRODUTO INT NOT NULL,
PRECO_TOTAL DECIMAL(12,4) NOT NULL,
ALIQUOTA_ICMS DECIMAL(4,2) NULL,
ICMS DECIMAL(12,4) NULL,
ALIQUOTA_PIS DECIMAL(4,2) NULL,
PIS DECIMAL(12,4) NULL,
ALIQUOTA_COFINS DECIMAL(4,2) NULL,
COFINS DECIMAL(12,4) NULL,
PRIMARY KEY (CODIGO_ITEM, CODIGO_NF),
FOREIGN KEY (CODIGO_NF) REFERENCES NF (CODIGO_NF),
FOREIGN KEY (CODIGO_PRODUTO) REFERENCES PRODUTO (CODIGO_PRODUTO)
);


-- TABELA DE PEDIDO
CREATE TABLE PEDIDO
(
CODIGO_PEDIDO INT NOT NULL,
NUMERO_PEDIDO CHAR(10) NOT NULL,
CODIGO_LOJA INT NOT NULL,
CODIGO_TIPO_LOJA INT NOT NULL,
CODIGO_CLIENTE INT NULL,
CODIGO_CLIENTE_PJ INT NULL,
PRIMARY KEY (CODIGO_PEDIDO, NUMERO_PEDIDO, CODIGO_TIPO_LOJA),
FOREIGN KEY (CODIGO_LOJA) REFERENCES SUPERMERCADO (CODIGO_LOJA),
FOREIGN KEY (CODIGO_TIPO_LOJA) REFERENCES TIPO_LOJA (CODIGO_TIPO_LOJA),
FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE_PF (CODIGO_CLIENTE),
FOREIGN KEY (CODIGO_CLIENTE_PJ) REFERENCES CLIENTE_PJ (CODIGO_CLIENTE_PJ)
);


-- TABELA DE LOJAS FÍSICAS
CREATE TABLE LOJA_FISICA
(
CODIGO_TIPO_LOJA INT NOT NULL,
CODIGO_PEDIDO INT NOT NULL,
CODIGO_LOJA INT NOT NULL,
PRIMARY KEY (CODIGO_TIPO_LOJA, CODIGO_PEDIDO),
FOREIGN KEY (CODIGO_TIPO_LOJA) REFERENCES TIPO_LOJA (CODIGO_TIPO_LOJA),
FOREIGN KEY (CODIGO_PEDIDO) REFERENCES PEDIDO (CODIGO_PEDIDO),
FOREIGN KEY (CODIGO_LOJA) REFERENCES SUPERMERCADO (CODIGO_LOJA)
);


-- TABELA DE E-COMMERCE
CREATE TABLE LOJA_WEB
(
CODIGO_TIPO_LOJA INT NOT NULL,
CODIGO_PEDIDO INT NOT NULL,
CODIGO_ESTOQUE INT NOT NULL,
CODIGO_LOJA INT NOT NULL,
PRIMARY KEY (CODIGO_TIPO_LOJA, CODIGO_PEDIDO),
FOREIGN KEY (CODIGO_TIPO_LOJA) REFERENCES TIPO_LOJA (CODIGO_TIPO_LOJA),
FOREIGN KEY (CODIGO_PEDIDO) REFERENCES PEDIDO (CODIGO_PEDIDO),
FOREIGN KEY (CODIGO_ESTOQUE) REFERENCES ESTOQUE (CODIGO_ESTOQUE)
FOREIGN KEY (CODIGO_LOJA) REFERENCES SUPERMERCADO (CODIGO_LOJA)
);

SHOW TABLES;



SELECT
 TABLE_NAME as TABELA,
 COLUMN_NAME as COLUNA,
 DATA_TYPE as TIPO,
COLUMN_KEY AS CHAVE,
EXTRA AS TABELA_ORIGEM,
EXTRA AS COLUNA_ORIGEM,
IS_NULLABLE AS NULO,
COLUMN_COMMENT AS DESCRICAO
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'PRODUTO'
ORDER BY Tabela, Coluna

SELECT * FROM PRODUTO;